server:
  port: 8099

pl:
  futurecollars:
    invoicing:
      db: file
      dir: classpath:invoices-json.txt

logging:
  level:
    org:
      springframework:
        boot: ERROR
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

springdoc:
  swagger-ui:
    enabled: true