spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

pl:
  futurecollars:
    invoicing:
      db: memory