pl:
  futurecollars:
    invoicing:
      db: file
      dir: classpath:invoices-json.txt
server:
  port: 8099

debug: false
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: INFO

springdoc:
  swagger-ui:
    enabled: true